/usr/local/Cellar/mysql/5.7.11

mysqladmin -uroot -ppassword create LABDBD

use LABDB;

CREATE TABLE PATIENT(PTNT_ID INT(16) AUTO_INCREMENT PRIMARY KEY,PTNT_NAME  VARCHAR(100),AGE INTEGER,GENDER   VARCHAR(10),STATUS   INT(4),patientAddress_ADDRESS_ID INT(16),PRIM_MOBILE   VARCHAR(16),SECOND_MOBILE   VARCHAR(16),EMAIL_ID VARCHAR(100),IMG_PATH VARCHAR(50));

CREATE TABLE ADDRESS(ADDRESS_ID INT(16) AUTO_INCREMENT PRIMARY KEY,ADD_LINE1  VARCHAR(100),ADD_LINE2   VARCHAR(100),ADD_LINE3   VARCHAR(100),CITY VARCHAR(100),ADD_TYPE VARCHAR(12),STATE   VARCHAR(32),ZIP  VARCHAR(12),COUNTRY VARCHAR(32));

CREATE TABLE DOCTOR(DOC_ID INT(16) AUTO_INCREMENT PRIMARY KEY,DOC_NAME  VARCHAR(100),DOC_BRANCH_CD INT(16),STATUS   INT(4),HOSP_NAME VARCHAR(100),DOC_DEGREE VARCHAR(256),DOC_SPEC VARCHAR(256),DOC_EXP VARCHAR(512),docAddress_ADDRESS_ID INT(16),PRIM_MOBILE   VARCHAR(16),SECOND_MOBILE   VARCHAR(16),EMAIL_ID VARCHAR(50),IMG_PATH VARCHAR(50));
ALTER TABLE DOCTOR ADD FEE INT(5)


CREATE TABLE LAB_OFFICE(LAB_OFFICE_ID INT(16) AUTO_INCREMENT PRIMARY KEY,LAB_NAME  VARCHAR(100),STATUS   INT(4),labAddress_ADDRESS_ID INT(16),LAB_OWNER VARCHAR(100), PRIM_MOBILE   VARCHAR(16),SECOND_MOBILE   VARCHAR(16),EMAIL_ID VARCHAR(100),IMG_PATH VARCHAR(50));

CREATE TABLE LAB_BRANCH(LAB_OFFICE_ID INT(16),FOREIGN KEY(LAB_OFFICE_ID) REFERENCES LAB_OFFICE(LAB_OFFICE_ID), LAB_BRANCH_CD INT(16)  AUTO_INCREMENT PRIMARY KEY,LAB_NAME  VARCHAR(100),STATUS   INT(4),labAddress_ADDRESS_ID INT(16),LAB_BR_OWNER VARCHAR(100), PRIM_MOBILE   VARCHAR(16),EMAIL_ID VARCHAR(100),IMG_PATH VARCHAR(100));

CREATE TABLE LAB_BRANCH_REP(LAB_REP_ID INT(16)  AUTO_INCREMENT PRIMARY KEY,PRIM_MOBILE   VARCHAR(16),REP_NAME VARCHAR(100),LAB_BRANCH_CD INT(16), FOREIGN KEY(LAB_BRANCH_CD) REFERENCES LAB_BRANCH(LAB_BRANCH_CD),STATUS   INT(4),IMG_PATH VARCHAR(50));

CREATE TABLE TESTS(TEST_ID INT(16) AUTO_INCREMENT PRIMARY KEY,TEST_NAME  VARCHAR(100),SHORT_NAME VARCHAR(20),STATUS   INT(4),LOWER_VALUE VARCHAR(10),UPPER_VALUE VARCHAR(10),UNITS VARCHAR(10),TEST_TYPE VARCHAR(10),BODY_ORGAN VARCHAR(100),DESCRIPTION VARCHAR(512),TEST_STEPS VARCHAR(512),IMG_PATH VARCHAR(50));

CREATE TABLE SYS_CODE(SYS_TYPE VARCHAR (24),SYS_VALUE INT(4),DESCRIPTION VARCHAR(100));
		
CREATE TABLE REVIEWS(REVIEW_ID INT(16),PTNT_ID INT(16),DOCTOR_ID INT(16),LAB_OFFICE_ID INT(16),LAB_BRANCH_CD INT(16),RATING INT(2),RATING_DT DATE,REVIEW VARCHAR(512));

CREATE TABLE TESTS_LAB(ID INT(16),LAB_OFFICE_ID INT(16),LAB_BRANCH_CD INT(16),TEST_ID INT(16),STATUS INT(4),HOME_PICK CHAR(1),FEE INT(5));


select * from CUSTOMER;
select * from ADDRESS;
select * from DOCTOR;
select * from LAB_OFFICE;
select * from LAB_BRANCH;
select * from LAB_BRANCH_REP;
